defmodule AoC do
  @moduledoc """
  Entry point for running Advent of Code solutions.

  A solution lives in a module named after its year and day, for example
  `MyApp.Solutions.Y23.Day01`, generated by `mix aoc.create`. Each solution
  module defines a `parse/2` function plus one function per part, `part_one/1`
  and `part_two/1`. `run/3` finds that module, makes sure the puzzle input is
  available locally, builds the problem with `parse/2`, and calls the requested
  part.

      case AoC.run(2023, 1, :part_one) do
        {:ok, answer} -> answer
        {:error, :not_implemented} -> :todo
      end

  The mix tasks `mix aoc.run` and `mix aoc.test` build on this function. You can
  also call it from your own tests to assert a part against the real input.
  """
  alias AoC.Input
  alias AoC.Mod

  @type input_path :: binary
  @type file :: input_path | %AoC.Input.TestInput{}
  @type part :: :part_one | :part_two
  @type input :: binary | File.Stream.t()
  @type problem :: any

  @doc """
  Runs the given `part` of the solution for `year` and `day`.

  `part` is `:part_one` or `:part_two`. The function loads the solution module
  for that year and day, ensures the puzzle input is available locally,
  downloading it when needed, builds the problem with the module's `parse/2`
  function, and calls the part function with the result.

  Returns `{:ok, answer}` with the value the part function returned. Returns
  `{:error, :not_implemented}` when no solution module exists for the year and
  day, or when the module does not export the requested part. Errors while
  reading or downloading the input are returned as `{:error, reason}`.
  """
  def run(year, day, part) when part in [:part_one, :part_two] do
    case find_module(year, day) do
      {:ok, module} -> do_run(year, day, module, part)
      {:error, _} = err -> err
    end
  end

  defp find_module(year, day) do
    with {:error, _} <- Code.ensure_loaded(Mod.module_name(year, day)),
         {:error, _} <- Code.ensure_loaded(Mod.legacy_module_name(year, day)) do
      {:error, :not_implemented}
    else
      {:module, mod} -> {:ok, mod}
    end
  end

  defp do_run(year, day, module, part) when is_atom(module) and part in [:part_one, :part_two] do
    with {:ok, input_path} <- Input.ensure_local(year, day),
         :ok <- ensure_part(module, part) do
      {:ok, call_part(module, part, input_path)}
    else
      {:error, :nofile} -> {:error, :not_implemented}
      {:error, _} = err -> err
    end
  end

  defp ensure_part(module, part) do
    if function_exported?(module, part, 1) do
      :ok
    else
      {:error, :not_implemented}
    end
  end

  defp call_part(module, part, input_path) do
    problem = generate_problem(module, part, input_path)
    apply(module, part, [problem])
  end

  defp generate_problem(module, part, input_path) do
    cond do
      function_exported?(module, :parse, 2) ->
        module.parse(input_path, part)

      function_exported?(module, :read_file, 2) and
          function_exported?(module, :parse_input, 2) ->
        input = module.read_file(input_path, part)
        _problem = module.parse_input(input, part)

      true ->
        raise "no function #{inspect(module)}.parse/2"
    end
  end
end
