defmodule AoC.Config do
  @moduledoc false

  def generate_comments?,
    do: !!Application.get_env(:aoc, :generate_comments, true)

  def prefix! do
    case Application.fetch_env(:aoc, :prefix) do
      {:ok, prefix} when is_atom(prefix) ->
        prefix

      _ ->
        raise """
        aoc prefix is not configured


        Please configure the prefix for modules generated by AoC:

            # config/config.exs
            config :aoc, prefix: MyApp.Solutions


        """
    end
  end
end
